name: Python CICD Kata
run-name: Python CICD Kata

on: [push]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install UV
        uses: astral-sh/setup-uv@v5
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: RUFF Foramat
  build:
    environment: poc
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create the build
        run: docker build . -t hugoalvarezu/next_python_cicd:latest
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to DockerHub
